import type { SplatMesh } from "@sparkjsdev/spark";

// Weak splats may contribute visually through blending, but their centers are
// unreliable collision samples. This is decoded alpha, not the PLY logit.
const MIN_COLLIDER_OPACITY = 0.05;

export function createPointCloudPly(splat: Pick<SplatMesh, "forEachSplat">): ArrayBuffer {
    const usable = (center: { x: number; y: number; z: number }, opacity: number): boolean =>
        Number.isFinite(Math.fround(center.x)) &&
        Number.isFinite(Math.fround(center.y)) &&
        Number.isFinite(Math.fround(center.z)) &&
        Number.isFinite(opacity) && opacity >= MIN_COLLIDER_OPACITY;

    let validCount = 0;
    splat.forEachSplat((_index, center, _scales, _quaternion, opacity) => {
        if (usable(center, opacity)) validCount += 1;
    });
    if (validCount === 0) {
        throw new Error("No usable collision samples (finite positions and opacity >= 0.05)");
    }

    const header = [
        "ply",
        "format binary_little_endian 1.0",
        "comment generated by collider-forge from filtered Gaussian centers",
        `element vertex ${validCount}`,
        "property float x",
        "property float y",
        "property float z",
        "end_header",
        "",
    ].join("\n");
    const headerBytes = new TextEncoder().encode(header);
    const result = new ArrayBuffer(headerBytes.length + validCount * 12);
    new Uint8Array(result, 0, headerBytes.length).set(headerBytes);
    const view = new DataView(result, headerBytes.length);
    let outputIndex = 0;
    splat.forEachSplat((_index, center, _scales, _quaternion, opacity) => {
        if (!usable(center, opacity)) return;
        const offset = outputIndex++ * 12;
        view.setFloat32(offset, center.x, true);
        view.setFloat32(offset + 4, center.y, true);
        view.setFloat32(offset + 8, center.z, true);
    });
    return result;
}
